language: node_js
node_js:
  - "14"

services:
  - mysql

env:
  global:
    - DB_TYPE=mysql
    - DB_HOST=127.0.0.1
    - DB_PORT=3306
    - DB_USER=root
    - DB_PASSWORD=password
    - DB_DATABASE=school-database
    - APP_URL=mywebsite.com
    - SUPPORT_EMAIL=support@${APP_URL}

before_script:
  - mysql -e 'CREATE DATABASE school-database;'
  - sleep 5

install:
  - npm install -g pnpm
  - cd school-be && pnpm install
  - cd ../school-fe && npm install

script:
  - cd school-be && pnpm run test
  - cd ../school-fe && npm run test